import { v4 as uuid } from 'uuid'

export const ListingData = [
   {
      listingId: '1',
      listingImage:
         'https://primer.com.ph/tips-guide/wp-content/uploads/sites/5/2015/12/canned-goods.jpg',
      listingName: 'Assorted Canned Goods',
      distance: '1 kilometer away',
      postTime: '10m ago',
   },
   {
      listingId: '2',
      listingImage:
         'https://farm5.staticflickr.com/4877/44971912865_5278910b09.jpg',
      listingName: 'Ligo Sardines',
      distance: '500 meters away',
      postTime: '35m ago',
   },
   {
      listingId: '3',
      listingImage:
         'https://c1.staticflickr.com/5/4158/33593402264_bedafb79d1_c.jpg',
      listingName: 'Lucky Me Pancit Canton',
      distance: '3 kilometers away',
      postTime: '50m ago',
   },
   {
      listingId: '4',
      listingImage:
         'https://cf.shopee.ph/file/be3e42ff04de23cebd0c1105e7ebd5b1',
      listingName: 'Fibisco biscuits',
      distance: '300 meters away',
      postTime: '1h ago',
   },
   {
      listingId: '5',
      listingImage:
         'https://cf.shopee.ph/file/eddfe3c0c7cb0f291a029b01dc8e7984',
      listingName: 'Organic eggs',
      distance: '1 kilometer away',
      postTime: '10m ago',
   },
   {
      listingId: '6',
      listingImage:
         'https://cf.shopee.ph/file/8b01c1f639a54c5dd54c02a35ac19ade',
      listingName: 'Cadbury biscuit',
      distance: '500 meters away',
      postTime: '35m ago',
   },
   {
      listingId: '7',
      listingImage:
         'https://cf.shopee.ph/file/1cb31d68b5008a0e8c428427f67c5710',
      listingName: 'Japonica Rice',
      distance: '3 kilometers away',
      postTime: '50m ago',
   },
   {
      listingId: '8',
      listingImage:
         'https://cf.shopee.ph/file/6ef4b658d3d25bda90dba4a23eabd9ef',
      listingName: 'Assorted biscuits',
      distance: '300 meters away',
      postTime: '1h ago',
   },
   {
      listingId: '9',
      listingImage:
         'https://cf.shopee.ph/file/54ea2d99554d33d52003ac756b3c602b',
      listingName: '1 pack tender juicy',
      distance: '1 kilometer away',
      postTime: '10m ago',
   },
   {
      listingId: '10',
      listingImage:
         'https://cf.shopee.ph/file/2315296425618aa856b068e01307fbee',
      listingName: 'Lucky me pancit canton',
      distance: '500 meters away',
      postTime: '35m ago',
   },
   {
      listingId: '11',
      listingImage:
         'https://cf.shopee.ph/file/02497683fcdb2296c145afdd7f50527c',
      listingName: 'Assorted biscuits',
      distance: '300 meters away',
      postTime: '1h ago',
   },
   {
      listingId: '12',
      listingImage:
         'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQapFieGJ2wKAH9Id3P1lqYJBP5JfUJpBN52sqPrfS928cmels4Mxl65KH-hRQypdI0g8U&usqp=CAU',
      listingName: 'Max condiments',
      distance: '3 kilometers away',
      postTime: '50m ago',
   },
]

const ListingDummyData = [
   {
      listingID: uuid(),
      donorID: uuid(),
      postTime: '',
      postDate: '',
      donationImage:
         'https://primer.com.ph/tips-guide/wp-content/uploads/sites/5/2015/12/canned-goods.jpg',
      donationName: 'Assorted Canned Goods',
      donationRecipient: 'Individual',
      donationCategory: 'Canned Goods',
      donationExpiry: '',
      donationNote: '',
      pickupLocation: '',
      locationLatitude: '',
      locationLongitude: '',
      donationStatus: '',
   },
   {
      listingID: uuid(),
      donorID: uuid(),
      postTime: '',
      postDate: '',
      donationImage:
         'https://farm5.staticflickr.com/4877/44971912865_5278910b09.jpg',
      donationName: '',
      donationRecipient: '',
      donationCategory: 'Individual',
      donationExpiry: '',
      donationNote: '',
      pickupLocation: '',
      locationLatitude: '',
      locationLongitude: '',
      donationStatus: '',
   },
   {
      listingID: uuid(),
      donorID: uuid(),
      postTime: '',
      postDate: '',
      donationImage: '',
      donationName: '',
      donationRecipient: '',
      donationCategory: '',
      donationExpiry: '',
      donationNote: '',
      pickupLocation: '',
      locationLatitude: '',
      locationLongitude: '',
      donationStatus: '',
   },
   {
      listingID: uuid(),
      donorID: uuid(),
      postTime: '',
      postDate: '',
      donationImage: '',
      donationName: '',
      donationRecipient: '',
      donationCategory: '',
      donationExpiry: '',
      donationNote: '',
      pickupLocation: '',
      locationLatitude: '',
      locationLongitude: '',
      donationStatus: '',
   },
]

export const users = [
   {
      id: uuid(),
      address: 'Food Bank',
      avatarUrl: '/static/images/avatars/avatar_3.png',
      createdAt: 1555016400000,
      email: 'panday.bayanihan@gmail.com',
      name: 'Panday Bayanihan',
      phone: '09123456789',
   },
   {
      id: uuid(),
      address: 'Individual',
      avatarUrl: '/static/images/avatars/avatar_4.png',
      createdAt: 1555016400000,
      email: 'cao.yu@gmail.com',
      name: 'Cao Yu',
      phone: '09123456789',
   },
   {
      id: uuid(),
      address: 'Community Pantry',
      avatarUrl: '/static/images/avatars/avatar_2.png',
      createdAt: 1555016400000,
      email: 'maginhawacp@gmail.com',
      name: 'Maginhawa Community Pantry',
      phone: '09123456789',
   },
   {
      id: uuid(),
      address: 'Community Pantry',
      avatarUrl: '/static/images/avatars/avatar_5.png',
      createdAt: 1554930000000,
      email: 'marikinacm@gmail.com',
      name: 'Marikina Community Pantry',
      phone: '09123456789',
   },
   {
      id: uuid(),
      address: 'Food Bank',
      avatarUrl: '/static/images/avatars/avatar_6.png',
      createdAt: 1554757200000,
      email: 'riseagainsthunger@gmail.com',
      name: 'Rise Against Hunger Philippines',
      phone: '09123456789',
   },
   {
      id: uuid(),
      address: 'Food Bank',
      avatarUrl: '/static/images/avatars/avatar_3.png',
      createdAt: 1555016400000,
      email: 'panday.bayanihan@gmail.com',
      name: 'Panday Bayanihan',
      phone: '09123456789',
   },
   {
      id: uuid(),
      address: 'Community Pantry',
      avatarUrl: '/static/images/avatars/avatar_2.png',
      createdAt: 1555016400000,
      email: 'cubaocp@gmail.com',
      name: 'Cubao Community Pantry',
      phone: '09123456789',
   },
   {
      id: uuid(),
      address: 'Individual',
      avatarUrl: '/static/images/avatars/avatar_8.png',
      createdAt: 1523048400000,
      email: 'emilee.simchenko@gmail.com',
      name: 'Emilee Simchenko',
      phone: '09123456789',
   },
   {
      id: uuid(),
      address: 'Food Bank',
      avatarUrl: '/static/images/avatars/avatar_3.png',
      createdAt: 1555016400000,
      email: 'panday.bayanihan@gmail.com',
      name: 'Panday Bayanihan',
      phone: '09123456789',
   },
   {
      id: uuid(),
      address: 'Individual',
      avatarUrl: '/static/images/avatars/avatar_10.png',
      createdAt: 1522702800000,
      email: 'merrile.burgett@gmail.com',
      name: 'Merrile Burgett',
      phone: '09123456789',
   },
]
